### ISSUE TITLE
SQS queue details changing every one hour

### ISSUE THREAD

**Issue by stalluri** [neptuneio/nagent#13]
![image](https://cloud.githubusercontent.com/assets/3118012/7783044/f2a14de0-00e7-11e5-90a3-47168f58e98f.png)

**Comment by buchireddy** [comment]
@stalluri This is an interesting but and I chased it down this evening :+1: 

Seems like the temporary credentials created by the root user have a maximum expiry of one hr where as other IAM users can create temp credentials with expiry up to 36 hrs. Hence, in production, all our temp credentials are valid up to one hr but on staging/dev it's up to 36 hrs.

@kirangollu We should create an IAM user for production and use those access keys instead of using root access keys. 

Please see this for reference:

# GetFederationToken—Custom Identity Broker

When you make a request to get temporary security credentials for a federated user, you make the request using the credentials of a specific user identity (an IAM user) and request a maximum duration for the temporary security credentials to remain valid. Credentials created by IAM users are valid for the specified duration, between 15 minutes and 36 hours; credentials created using root account credentials have a maximum of one hour. The permissions available with the temporary security credentials are determined by an IAM policy that you pass when you call GetFederationToken.

**Comment by kirangollu** [comment]
yep, we should do that. there was another bug where I said we were doing too much logging on agent (looks like - that was also because of this).

**Comment by buchireddy** [comment]
Closing this since this is server side issue. Logged separate issue to track it on server side.
